12 chore add tests for request utils
dvo-dev/go-get-started pull request #14
Opened 2022-08-26 02:17 UTC by alexander-ma

# Summary

### Related Issues

- Completes #69
- Partial fix #420

### Contributors

- @github: implementer
- @deeznutz: SQL consultation

### Affected Modules

- `pkg/database`
- `cmd/webapp`

### Description

This is where you should describe the contents of this pull request at a **high level**, aim for 2-3 paragraphs of content but more is always better than less.

Try to describe the changes in a "did X by Y", e.g. improved logging by adding multiple levels vs improved logging.

# Dependency Interactions

If altering configurations/usage of external depedencies such as caches, databases, etc. describe it in this area.

### Redis
Adding usage for session caches.

### Elasticsearch
Change lookup parameters

# Testing (Unit/Integration/Performance)

Describe tests modified or added for coverage of the PR's contents.

If something is not testable, explain here as well.

# Points of Attention

Call out anything you notice that may have an affect on others work, past or future.

This includes potential areas of refactorization, unavoidable code stinks, improved implementation methodology learned, etc.

2022-08-26 04:58 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +		r.ParseForm()
lint - check error return

2022-08-26 04:58 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +		r.ParseForm()
lint - check error return

2022-08-26 04:58 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +		r.ParseForm()
lint - check error return

2022-08-27 01:45 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +// Separate test functions for each wrapper tested, use sub tests if needed
These sound like preliminary notes rather than describing the actual tests

2022-08-27 01:47 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +	getTestHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
I'd use two subtests combining the `GET` tests, something like:

```go
func TestRequests_GETRequest(t *testing.T) {
    t.Run("basic", func() {
        ...
    }

    t.Run("nil params", func() {
        ...
    }
}
```

2022-08-28 04:32 UTC, alexander-ma commented on pkg/utils/requests/requests_test.go
> +// Separate test functions for each wrapper tested, use sub tests if needed
Removed these comments as they were for my notes.

2022-08-28 04:33 UTC, alexander-ma commented on pkg/utils/requests/requests_test.go
> +	getTestHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
This is a good suggestion, thanks.

2022-08-29 05:34 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +			assert.Equal(t, r.URL.Query().Get("param1"), "foobar", "Param values do not match")
_nit_  - u can extra tryhard this shit by setting consts for `param1` & `foobar` at the start - this makes it easier to change all the references at once up 2 u tho

2022-09-01 01:48 UTC, dvo-dev requested changes

2022-09-01 01:48 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +		getTestHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
no testing at all?

2022-09-01 01:48 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +		value := []byte("value")
no assertions on value or uploadData? this is pretty important

2022-09-01 01:48 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +		params := map[string]string{}
whats the purpose of passing `string{}`? also no assertions?

2022-09-06 16:13 UTC, alexander-ma commented on pkg/utils/requests/requests_test.go
> +		params := map[string]string{"param1": "foobar"}
Added assertion

2022-09-06 16:13 UTC, alexander-ma commented on pkg/utils/requests/requests_test.go
> +		value := []byte("value")
Updated unit test to assert

2022-09-06 16:13 UTC, alexander-ma commented on pkg/utils/requests/requests_test.go
> +		getTestHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
Updated.

2022-09-06 16:15 UTC, alexander-ma commented on pkg/utils/requests/requests_test.go
> +		params := map[string]string{}
Removed unused params map and added assertions.

2022-09-06 16:29 UTC, alexander-ma commented on pkg/utils/requests/requests_test.go
> +			assert.Equal(t, r.URL.Query().Get("param1"), "foobar", "Param values do not match")
adding tech debt

2022-09-06 20:12 UTC, dvo-dev requested changes

2022-09-06 20:12 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +		value := []byte("value")
are you actually checking for this value in the test handler?

2022-09-06 20:17 UTC, dvo-dev commented on pkg/utils/requests/requests_test.go
> +			assert.Equal(t, "13", headers["Content-Length"][0])
what is this 13 value?

2022-09-09 16:08 UTC, alexander-ma commented on pkg/utils/requests/requests_test.go
> +			assert.Equal(t, "13", headers["Content-Length"][0])
13 will come from `r.ContentLength`

2022-09-09 16:58 UTC, alexander-ma commented on pkg/utils/requests/requests_test.go
> +		value := []byte("value")
Added check to look for byte array.

2022-09-09 17:31 UTC, dvo-dev approved these changes
LGTM

2022-09-09 18:02 UTC, merged

2022-09-09 18:02 UTC, alexander-ma commented
Pog